[project]
name = 'Decentralized-Specialized-Fashion-Design-Protection'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.design-registration]
path = 'contracts/design-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.timestamp-verification]
path = 'contracts/timestamp-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
